"""Quants

Revision ID: 0f741554aadd
Revises: 5b52890bc276
Create Date: 2025-11-08 13:05:09.341007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f741554aadd'
down_revision: Union[str, None] = '5b52890bc276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantum_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.drop_column('quantum_config')

    # ### end Alembic commands ###
