"""Letters-upd

Revision ID: 1a88b8904680
Revises: 9004c4c79c6b
Create Date: 2025-11-04 11:22:12.419516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a88b8904680'
down_revision: Union[str, None] = '9004c4c79c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
