"""Models annotations

Revision ID: 672a2ce642cd
Revises: 6d16a2f53676
Create Date: 2025-11-04 23:10:45.608146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672a2ce642cd'
down_revision: Union[str, None] = '6d16a2f53676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('letters', schema=None) as batch_op:
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_parsing_configs_name'), type_='unique')

    with op.batch_alter_table('ref_filters_configs', schema=None) as batch_op:
        batch_op.alter_column('filter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('config_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_filters_configs', schema=None) as batch_op:
        batch_op.alter_column('config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('filter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_parsing_configs_name'), ['name'])

    with op.batch_alter_table('letters', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('letter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
