"""Letters-upd_letter_id_ref

Revision ID: 6d16a2f53676
Revises: 1a88b8904680
Create Date: 2025-11-04 16:53:37.226945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d16a2f53676'
down_revision: Union[str, None] = '1a88b8904680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attachments_letter_id_letters'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attachments_letter_id_letters'), 'letters', ['letter_id'], ['letter_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attachments_letter_id_letters'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attachments_letter_id_letters'), 'letters', ['letter_id'], ['id'])

    # ### end Alembic commands ###
