"""Letters

Revision ID: 9004c4c79c6b
Revises: 235304b85c3d
Create Date: 2025-11-04 11:20:48.737019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9004c4c79c6b'
down_revision: Union[str, None] = '235304b85c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_letters_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_letters'))
    )
    with op.batch_alter_table('letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_letters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_letters_letter_id'), ['letter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_letters_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], name=op.f('fk_attachments_letter_id_letters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_letter_id'), ['letter_id'], unique=False)

    op.create_table('ref_filters_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['parsing_configs.id'], name=op.f('fk_ref_filters_configs_config_id_parsing_configs')),
    sa.ForeignKeyConstraint(['filter_id'], ['emailfilters.id'], name=op.f('fk_ref_filters_configs_filter_id_emailfilters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_filters_configs'))
    )
    with op.batch_alter_table('ref_filters_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ref_filters_configs_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_filters_configs_filter_id'), ['filter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ref_filters_configs_id'), ['id'], unique=False)

    with op.batch_alter_table('emailfilters', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_emailfilters_senders'), ['senders'])

    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_parsing_configs_name'), ['name'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_settings_setting'), ['setting'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vendors_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendors_name'), type_='unique')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_settings_setting'), type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_parsing_configs_name'), type_='unique')

    with op.batch_alter_table('emailfilters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_emailfilters_senders'), type_='unique')

    with op.batch_alter_table('ref_filters_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ref_filters_configs_id'))
        batch_op.drop_index(batch_op.f('ix_ref_filters_configs_filter_id'))
        batch_op.drop_index(batch_op.f('ix_ref_filters_configs_config_id'))

    op.drop_table('ref_filters_configs')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_letter_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_letters_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_letters_letter_id'))
        batch_op.drop_index(batch_op.f('ix_letters_id'))

    op.drop_table('letters')
    # ### end Alembic commands ###
