"""QuantsStr

Revision ID: c827641f3066
Revises: 0f741554aadd
Create Date: 2025-11-08 13:38:36.478807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c827641f3066'
down_revision: Union[str, None] = '0f741554aadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.alter_column('quantum_config',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.alter_column('quantum_config',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
