"""ParsingConfig Extend

Revision ID: dd00d71299b7
Revises: 7a5bd492b4ac
Create Date: 2025-11-06 12:31:55.591699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd00d71299b7'
down_revision: Union[str, None] = '7a5bd492b4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('to_common', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('save_original', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('save_parsed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsing_configs', schema=None) as batch_op:
        batch_op.drop_column('save_parsed')
        batch_op.drop_column('save_original')
        batch_op.drop_column('to_common')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
