"""ParserConfigExtend

Revision ID: e6683362d137
Revises: 5bdad1d5ec17
Create Date: 2025-11-03 14:12:57.421900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6683362d137'
down_revision: Union[str, None] = '5bdad1d5ec17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsing_configs', sa.Column('filename_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsing_configs', 'filename_template')
    # ### end Alembic commands ###
